name: bloc_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  equatable: ^2.0.8
  fpdart: ^1.2.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  uuid: ^4.5.2
  string_validator: ^1.2.0
  stream_transform: ^2.1.1

  core:
    path: ../packages/core
  domain:
    path: ../packages/domain
  data_supabase:
    path: ../packages/data_supabase
  build_runner: ^2.11.1
  injectable_generator: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
