name: data_supabase
description: "The supabase data layer shared across all apps."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  fpdart: ^1.2.0
  json_annotation: ^4.10.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2

  core:
    path: ../core
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
