name: domain
version: 0.0.1
description: "The domain layer shared across all apps."
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  fpdart: ^1.2.0
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
